### ISSUE TITLE
Test - Homepage: Video on Carousel

### ISSUE THREAD

**Issue by robertfrankiii** [iwu/iwu-website#75]
Just a question. Will we have the ability to add video to the homepage carousel with the redesign, or should that wait for later down the road? I know this is something we've all discussed, but I can't remember the verdict.

**Comment by michaelcgorman** [comment]
Yes, it can be done. If there isn't any audio and you don't mind it playing continuously in a loop while the carousel continues rotating, you can use code like:
`<a class="item"><iframe width="100%" height="100%" src="https://www.youtube.com/embed/2FWUp2HCxr8?rel=0&amp;controls=0&amp;showinfo=0&amp;autohide=1&amp;autoplay=1&amp;loop=1&amp;modestbranding=1&amp;playsinline=1" frameborder="0" allowfullscreen></iframe></a>`
If you want it to play/pause automatically when it shows on-screen, I'll have to use the YouTube JS API rather than a simpler iframe embed. Doable, but it'll take a little more thought.

**Comment by robertfrankiii** [comment]
Personally, I think what you said we can already do is great (especially since we don't have any videos for this use at the moment). I think the play/pause can wait until... some other time. Thanks for the info!
